version: '3.8'

services:
  phoenix-zplace-web:
    build: .
    container_name: phoenix-zplace-website
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Montage en lecture seule pour la sécurité
      - ./ZPlace:/app/ZPlace:ro
    networks:
      - phoenix-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phoenix-zplace.rule=Host(`zplace.phoenix-rp.com`)"
      - "traefik.http.services.phoenix-zplace.loadbalancer.server.port=3000"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

networks:
  phoenix-network:
    driver: bridge
